Repository Kumoh-talk/kumoh-talk-Frontend, pull requests merged in 2025-03, with the labels that each got.

#53 fix: 신청서 리스트 min-height 추가
  src/app/components/recruitment-boards/list/listTable.module.scss
  src/app/recruitment-boards/list/page.module.scss
  src/app/recruitment-boards/list/page.tsx
Labels: 🐛 Bug

#54 이미지 추가 확장 기능 구현
  src/app/_mixin.scss
  src/app/components/post/ImageNode/ImageComponent.module.scss
  src/app/components/post/ImageNode/ImageComponent.tsx
  src/app/components/post/ImageNode/ImageNode.tsx
  src/app/globals.css
  src/app/post/page.module.scss
  src/app/post/page.tsx
Labels: ✨Feature

#55 첨부 파일 추가 기능 구현
  src/app/assets/svg/Editor/FileSvg.tsx
  src/app/components/post/EditorMenu/EditorMenu.tsx
  src/app/components/post/EditorMenuButton/EditorFileButton.tsx
  src/app/components/post/FileNode/FileComponent.module.scss
  src/app/components/post/FileNode/FileComponent.tsx
  src/app/components/post/FileNode/FileNode.ts
  src/app/post/page.tsx
Labels: ✨Feature

#56 링크 추가 기능 구현
  package.json
  src/app/_mixin.scss
  src/app/assets/svg/CheckSvg.tsx
  src/app/assets/svg/Editor/LinkSvg.tsx
  src/app/components/post/EditorMenu/EditorMenu.tsx
  src/app/components/post/EditorMenuButton/EditorLinkButton.tsx
  src/app/components/post/EditorMenuButton/EditorLinkForm.tsx
  src/app/components/post/EditorMenuButton/EditorMenuButton.module.scss
  src/app/lib/hooks/common/useClickOutside.tsx
  src/app/lib/hooks/common/useOverlay.ts
  src/app/lib/hooks/post/useEditorLink.ts
  src/app/post/page.tsx
  yarn.lock
Labels: ✨Feature

#66 세미나 신청 폼 제출 처리 및 구현
  src/app/api/[domain]/route.ts
  src/app/apply/page.tsx
  src/app/components/apply/Checkbox/Checkbox.tsx
  src/app/components/apply/Field/CheckboxField.tsx
  src/app/components/apply/Field/SelectField.tsx
  src/app/components/apply/FormFields/FormFields.tsx
  src/app/components/apply/Select/Select.tsx
  src/app/components/apply/SeminarApplyForm/SeminarApplyForm.module.scss
  src/app/components/apply/SeminarApplyForm/SeminarApplyForm.tsx
  src/app/components/recruitment-boards/apply/ParseTypeToField.tsx
  src/app/components/recruitment-boards/post/Choice/Choice.module.scss
  src/app/components/recruitment-boards/post/Choice/Choice.tsx
  src/app/components/recruitment-boards/post/Field/CheckboxField.tsx
  src/app/components/recruitment-boards/post/Field/ChoiceField.tsx
  src/app/lib/apis/apply/seminarApplication.ts
  src/app/lib/hooks/apply/useFormAction.ts
  src/app/lib/schemas/seminarFormSchema.ts
  src/app/lib/utils/common/checkLogin.ts
  src/app/lib/utils/common/checkUserRole.ts
  src/app/lib/utils/post/parseAdditionalInfo.ts
Labels: ✨Feature

#131 이미지, 첨부파일, 링크 북마크를 포함한 임시 저장 및 자동 저장 구현
  package.json
  src/app/assets/svg/Editor/TrashSvg.tsx
  src/app/components/post/Draft/Draft.module.scss
  src/app/components/post/Draft/Draft.tsx
  src/app/components/post/Draft/DraftItem.tsx
  src/app/components/post/Draft/DraftList.tsx
  src/app/components/post/EditorMenu/EditorMenu.module.scss
  src/app/components/post/EditorMenu/EditorMenu.tsx
  src/app/components/post/EditorMenuButton/EditorFileButton.tsx
  src/app/components/post/EditorMenuButton/EditorImageButton.tsx
  src/app/components/post/FileNode/FileComponent.module.scss
  src/app/components/post/FileNode/FileNode.ts
  src/app/components/post/HashTag/HashTag.module.scss
  src/app/components/post/HashTag/HashTag.tsx
  src/app/components/post/Header/Header.module.scss
  src/app/components/post/Header/Header.tsx
  src/app/components/post/ImageNode/ImageComponent.module.scss
  src/app/components/post/ImageNode/ImageNode.tsx
  src/app/components/post/LinkPreview/LinkPreviewNode.ts
  src/app/components/post/Title/Title.module.scss
  src/app/components/post/Title/Title.tsx
  src/app/lib/apis/post/boards.ts
  src/app/lib/apis/post/files.ts
  src/app/lib/apis/post/saveDraft.ts
  src/app/lib/apis/post/saveFiles.ts
  src/app/lib/constants/post/board.ts
  src/app/lib/contexts/post/PostContentContext.tsx
  src/app/lib/contexts/post/PostEditorProvider.tsx
  src/app/lib/contexts/post/PostModeContext.tsx
  src/app/lib/contexts/post/PostProvider.tsx
  src/app/lib/hooks/common/useIntersectionObserver.ts
  src/app/lib/hooks/common/usePreventUnload.ts
  src/app/lib/hooks/post/useAutoSave.ts
  src/app/lib/hooks/post/useDrafts.ts
  src/app/lib/hooks/post/useInfiniteFetcher.ts
  src/app/lib/hooks/post/useInitBoardId.ts
  src/app/lib/hooks/post/useSaveDraft.ts
  src/app/lib/types/post/boards.ts
  src/app/lib/utils/post/dateFormatter.ts
  src/app/lib/utils/post/editorFileUtils.ts
  src/app/post/page.module.scss
  src/app/post/page.tsx
  yarn.lock
Labels: ✨Feature, ⛏ Refactor

#134 공지사항 작성 기능 구현
  src/app/components/common/header/writeArea/WriteArea.tsx
  src/app/components/common/header/writeArea/writeButton/WriteButton.tsx
  src/app/components/common/header/writeArea/writeButton/selectBubble/SelectBubble.tsx
  src/app/lib/apis/auth.ts
  src/app/lib/apis/post/saveDraft.ts
  src/app/lib/contexts/post/PostContentContext.tsx
  src/app/lib/hooks/post/useAutoSave.ts
  src/app/lib/hooks/post/useInitBoardId.ts
  src/app/lib/hooks/post/useSaveDraft.ts
  src/middleware.ts
Labels: ✨Feature

#137 에디터 이미지 copy & paste, drag & drop, 대표 이미지 기능 구현
  src/app/components/post/Draft/DraftItem.tsx
  src/app/components/post/ImageNode/ImageComponent.module.scss
  src/app/components/post/ImageNode/ImageComponent.tsx
  src/app/components/post/ImageNode/ImageNode.tsx
  src/app/lib/apis/post/saveFiles.ts
  src/app/lib/hooks/post/useAutoSave.ts
  src/app/lib/hooks/post/useDrafts.ts
  src/app/lib/hooks/post/useSaveDraft.ts
  src/app/lib/utils/post/editorFileUtils.ts
Labels: ✨Feature

#138 세미나 / 공지사항 작성 글 게시 기능 구현
  src/app/assets/svg/Editor/MinusSvg.tsx
  src/app/assets/svg/Editor/PlusSvg.tsx
  src/app/components/post/Header/Header.tsx
  src/app/components/post/Publish/Publish.module.scss
  src/app/components/post/Publish/Publish.tsx
  src/app/lib/apis/post/boards.ts
  src/app/lib/apis/post/saveDraft.ts
  src/app/lib/apis/post/saveFiles.ts
  src/app/lib/hooks/post/usePublish.ts
Labels: ✨Feature

#140 공지사항 조회 페이지 구현
  package.json
  src/app/assets/svg/Editor/MoreVerticalSvg.tsx
  src/app/components/common/header/writeArea/WriteArea.tsx
  src/app/components/common/header/writeArea/writeButton/WriteButton.tsx
  src/app/components/common/header/writeArea/writeButton/selectBubble/SelectBubble.tsx
  src/app/components/front/noticeList/NoticeItem.tsx
  src/app/components/notice/Board.module.scss
  src/app/components/notice/Board.tsx
  src/app/components/post/BoardInit/BoardInit.tsx
  src/app/lib/apis/notice/notice.ts
  src/app/lib/utils/post/dateFormatter.ts
  src/app/notice/[id]/page.module.scss
  src/app/notice/[id]/page.tsx
  src/app/post/page.tsx
  yarn.lock
Labels: ✨Feature

#182 유저가 인적사항을 작성하지 않았을 시, 권한 문제에 대한 사용자 피드백 추가
  src/app/components/notice/Board.tsx
Labels: 🐛 Bug

#183 메인 홈 공지사항 레이아웃 및 게시글 조회 시 개행 문제 수정
  src/app/assets/svg/BoardViewSvg.tsx
  src/app/components/front/noticeList/noticeItem.module.scss
  src/app/components/front/seminarList/SeminarItem.tsx
  src/app/components/front/seminarList/seminarItem.module.scss
  src/app/components/front/seminarList/seminarList.module.scss
  src/app/components/notice/Board.module.scss
Labels: 🐛 Bug, ⛏ Refactor

#189 이미지 / 첨부파일 크기 제한 적용
  src/app/components/common/loader/Loader.module.scss
  src/app/components/common/loader/Loader.tsx
  src/app/components/post/EditorMenuButton/EditorFileButton.tsx
  src/app/components/post/EditorMenuButton/EditorImageButton.tsx
  src/app/components/post/ImageNode/ImageNode.tsx
  src/app/components/post/Publish/Publish.tsx
  src/app/components/profile/ImageEditMenu.tsx
  src/app/components/profile/ProfileContent.tsx
  src/app/lib/constants/common/file.ts
  src/app/profile/page.tsx
Labels: ✨Feature, ⛏ Refactor
